from selenium import webdriver
from selenium.webdriver.common.by import By
from time import time

# Keep Chrome browser open after program finishes
chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option("detach", True)

# Create and configure the Chrome webdriver
driver = webdriver.Chrome(options=chrome_options)

# Navigate to cookie clicker classic
driver.get("https://orteil.dashnet.org/experiments/cookie/")

# Find cookie and store elements for later use
cookie = driver.find_element(By.ID, value="cookie")
store = driver.find_element(By.ID, value="store")

def check_buttons():
    """Attempts to find elements in the store who do not have the class 'grayed' and inserting them into a list.
    If any elements exist, it clicks the last element in the list without the 'grayed' class."""
    try:
        buttons = store.find_elements(By.CSS_SELECTOR, value="div :not(.grayed) > b ")
        buttons[-1].click()
    except:
        pass

# Sets timers for when the script stops running or times out.
timeout_5_sec = time() + 5
timeout = 300
end_time = time() + timeout

# Runs the script and checks for upgrades every 5 seconds. Purchases the most expensive upgrade every 5 seconds.
# The while loop ends after 5 minutes.
while time() < end_time:
    cookie.click()
    if int(time()) % 5 == 0:
        check_buttons()
# Finds the value of the cookies per second generated by the script, and prints it to the console.
cookies_second = driver.find_element(By.ID, value="cps")
print(cookies_second.text)